name: .NET Desktop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.8.x'
      
      - name: Restore NuGet packages
        run: nuget restore FaceDetectionApp.sln

      - name: Build solution
        run: msbuild FaceDetectionApp.sln /p:Configuration=Release
